title: Beginner App Inventor Sushi Cards
hero_image: images/banner.png
description: Learn how to use App Inventor to make a quiz app
theme: green
version: 1
listed: true
copyedit: true
last_tested: "2018-04-30"
steps:
  - title: Introduction
  - title: What you will need
  - title: Getting set up
  - title: Creating a question
  - title: Checking answers
  - title: Multiple questions
  - title: Wrapping up
  - title: What next?
