---
title: Global food app
hero_image: images/banner.png
description: Learn how to use App Inventor to make a quiz app
theme: green
listed: true
copyedit: true
curriculum: ''
interests: ''
technologies: ''
site_areas: coderdojo, projects
hardware: ''
software: ''
version: 3.0.0
last_tested: '2018-04-30'
steps:
  - 
    title: Introduction
  - 
    title: Getting set up
  - 
    title: Creating a question
    completion:
      - engaged
  - 
    title: Checking answers
  - 
    title: Multiple questions
  - 
    title: Wrapping up
    completion:
      - internal
  - 
    title: What next?
