---
title: التطبيق الغذاء العالمي
hero_image: images/banner.png
description: تعرف على كيفية استخدام App Inventor لإنشاء تطبيق اختبار
theme: green
listed: true
copyedit: true
curriculum: ''
interests: ''
technologies: ''
site_areas: coderdojo, projects
hardware: ''
software: ''
version: 3.0.0
last_tested: '2018-04-30'
steps:
- title: المقدمة
  completion: engaged
- title: هيا بنا لنبدأ
- title: صنع السؤال
- title: التحقق من الإجابات
- title: أسئلة متعددة
  completion: internal
- title: إنتهيت تقريباً
- title: ما التالي؟
